# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uVcnvIkbjgtLDuDxoR9mZzyrkAyYyZfu
"""

from numpy import *
import numpy as np
from csv import DictReader


f=open('/content/Housing Price data set.csv', 'r')
rd=DictReader(f)
x=[]
y=[]
for i in rd:
    x.append([1.0,float(i['lotsize']),float(i['bedrooms']),float(i['bathrms'])])
    y.append([float(i['price'])])
x_test=[]
x_train=[]
y_test=[]
y_train=[]
flg=0
for i in range(len(x)):
    if flg:
        x_test.append(x[i])
        y_test.append(y[i])
    else:
        x_train.append(x[i])
        y_train.append(y[i])
    if len(x_train)>=0.7*len(x):
        flg=1

theta=dot(dot(linalg.inv(dot(transpose(x_train),x_train)),transpose(x_train)),y_train)
print(theta)
pred=[]
for i in range(len(x_test)):
    pred.append([(x_test[i]@theta)[0],y_test[i][0]])
er=mean([(i[0]-i[1])*(i[0]-i[1]) for i in pred])
print(er)
print(sqrt(er))




L = np.identity(4, dtype=float)
L[0][0] = 0
# print("Matrix L : \n", L)

theta2=dot(dot(linalg.inv(dot(transpose(x_train),x_train)+28*L),transpose(x_train)),y_train)
pred1 = []

for i in range(len(x_test)):
    pred1.append([x_test[i]@theta2, y_test[i]])
mse1 = mean([(i[0]-i[1])*(i[0]-i[1]) for i in pred1])
rmse1 = math.sqrt(mse1)
print(mse1)
print(sqrt(mse1))